# ğŸ“¦ ArUco Cube STL Generator

Generate a **hollow calibration cube** and **multicolor ArUco marker plates** entirely in Python â€” designed for **robust visual detection** at up to ~**1.5 m** using the **Intel RealSense D455 RGB camera**, and optimized for **Bambu Lab AMS** multi-color printing.

This project is intentionally **simple and hackable** â€” no GUI, no over-engineering, just:

> **Python â†’ STL â†’ slice â†’ print**

This version includes:
- A **seam-hiding bezel** on each plate
- **Face-up, matte marker printing** (no bed gloss)
- **Timestamped output folders** for reproducible iteration
- A **self-documenting `run_info.txt`** saved with every STL batch
- Geometry tweaks for **large unsupported internal bridges**
- A **printing-friendly â€œattic roofâ€** to reduce long internal bridging
- **Mitered (tapered) slot edges** to avoid 90Â° â€œstart in airâ€ overhangs

---

## ğŸš€ Features

### ğŸ§Š Cube Generator
- Hollow cube with:
  - **Outer edge: 150 mm**
  - Wall thickness: **3.2 mm** (configurable)
  - **Five recessed faces** (top, +X, âˆ’X, +Y, âˆ’Y)
  - Optional **open bottom** (rim retained for stiffness)
- Recess depth: **2.4 mm**, matching plate thickness
- Designed to be printed **support-free**

#### ğŸ§± Printing-friendly internal geometry
To make the cube printable without supports (and with cleaner bridging), the cube includes:

**1) Roof thickener (inside-only)**
- Adds material *from the inside* at the roof to stiffen the large internal span
- Controlled by: `roof_extra_thickness_mm`
- Does **not** change the cubeâ€™s external dimensions

**2) â€œAttic roofâ€ (internal slopes)**
- Adds shallow internal slopes along the inside walls up to the roof underside
- Reduces the *effective* bridge distance and improves first bridge-layer anchoring
- Controlled by:
  - `attic_drop_mm` (vertical drop at the walls)
  - `attic_margin_mm` (overlap safety margin)

---

### ğŸ§© Slot System (Plates + Cube)
The plate system is designed for **repeatable press-fit assembly** and better printability.

#### ğŸ”» Mitered (tapered) slot edges
The cubeâ€™s recessed slots are **tapered** so the slot has a wider opening and a slightly smaller inner face.

**Why it helps**
- Avoids sharp internal 90Â° ceilings where extrusion would otherwise â€œstart in airâ€
- Improves print reliability on the slot roof edges
- Makes insertion smoother and reduces edge scraping

**Key parameters**
- `slot_depth` â€” depth of the recess
- `slot_miter_mm` â€” taper amount (for a true 45Â° draft, set equal to `slot_depth`)

> âš ï¸ If you change taper settings, you must reprint plates so their plug taper matches.

#### ğŸ›¡ Attic keepout (important)
The attic and roof thickener **add material** on the inside of the cube. A keepout region is applied around the **top slot cavity** to prevent boolean overlap.

- Controlled by: `attic_keepout_margin_mm`
- Ensures the **top slot surface stays planar and flat**

---

### ğŸ§© ArUco Plate Generator
- **4Ã—4 ArUco markers** (`DICT_4X4_50`, `borderBits = 1`)
- **2.4 mm thick plug plates**
- **0.8 mm raised black cells** for AMS two-color printing
- **Integrated top-face bezel (flange)**:
  - Overlaps cube slot opening
  - Hides seam and shadow lines
  - Improves detection stability
  - Allows **face-up printing** (matte marker surface)

### ğŸ· Plate ID Text
- Optional **embossed ID text** in the white quiet zone
- Implemented with a **robust raster fallback**
- Designed to be slicer-safe

---

## ğŸ§  Design Rationale (Intel RealSense D455)

### Camera assumptions
- RGB resolution: **1280 px horizontal**
- Horizontal FOV: **~86Â°**
- Marker grid: **6Ã—6 cells** (4Ã—4 data + border)

### Pixels per degree
```
1280 px / 86Â° â‰ˆ 14.9 px/degree
```

### Target pixels per cell
- â‰¥ 6 px/cell â†’ borderline
- â‰¥ 8 px/cell â†’ reliable (design target)
- â‰¥ 10 px/cell â†’ very robust

---

## ğŸ“ Marker Size Calculation (150 mm Cube)

Target: **1.5 m detection distance**, â‰¥ **8 px/cell**

```
marker_px â‰ˆ 48 px
angular_width â‰ˆ 3.22Â°
physical_width â‰ˆ 84 mm
```

â¡ï¸ **Minimum recommended marker width: ~84 mm**

Mapped to cube geometry:
- Slot size: `150 Ã— 0.85 = 127.5 mm`
- Plate size: `â‰ˆ 127.1 mm`
- Marker area: `â‰ˆ 112 mm`
- Cell size: `â‰ˆ 18.7 mm`

---

## âš ï¸ Bambu Studio Bridge Warning

Bambu Studio may report **unsupported overhangs** due to the large internal roof bridge.

âœ” Geometry is intentional
âœ” Designed for support-free printing
âœ” Warning can be safely ignored

**Recommended slicer tweaks**:
- Bridge speed: **15 mm/s**
- Slightly lower nozzle temperature if needed
- Increase part cooling during bridges

---

## â–¶ï¸ Running the Generator

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python -m src.aruco_cube_gen
```

---

## ğŸ“¦ Output Layout

Each run creates a timestamped folder:

```
out_stls_YYYY-MM-DD_HH-MM-SS/
â”œâ”€â”€ cube_with_slots.stl
â”œâ”€â”€ plate_base.stl
â”œâ”€â”€ plate_base_id0.stl
â”œâ”€â”€ plate_marker_id0.stl
â”œâ”€â”€ plate_combined_id0.stl
â”œâ”€â”€ ...
â””â”€â”€ run_info.txt
```

---

## ğŸ§± Assembly

1. Press-fit plates into cube recesses
2. Bezel hides seam and shadow lines
3. Optional tiny CA glue dot on **back corners only**
4. Use cube with the **open face down**

---

## ğŸ“œ License
MIT License

